### PR TITLE
Update maven repository

### PR DESCRIPTION
**Pull request by Cleiton-D**
Update address for maven central repository

### CODE REVIEW

**Comment by Maxim-Mazurok** [comment]
Would be great to publish this to npm @joeferner
Thanks!

**Comment by Maxim-Mazurok** [comment]
Also, I'm getting this error with this change:
```
501 HTTPS Required. 
Use https://repo1.maven.org/maven2/
More information at https://links.sonatype.com/central/501-https-required
```
changing protocol to `https` solves the problem

**Comment by Maxim-Mazurok** [comment]
Fix: https://github.com/joeferner/node-java-maven/pull/33

**Comment by joeferner** [comment]
published v0.1.2

**Pull request merged**
